name: PyPi publish

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine cibuildwheel build

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
          #CIBW_TEST_COMMAND: ""
        run: cibuildwheel --output-dir wheelhouse

      - name: Build source distribution
        run: python -m build --sdist --outdir wheelhouse

      - name: Check if wheelhouse artifact exists
        run: ls -la wheelhouse

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: python -m twine upload --verbose -u "${TWINE_USERNAME}" -p "${TWINE_PASSWORD}" wheelhouse/*